SELECT * FROM customer LIMIT 20;

--01 What is the total revenue generated by the male vs female customers?
SELECT gender, SUM("purchase_amount_(usd)") AS revenue
FROM customer
GROUP BY gender;


--02 Which customers used a discount but still spent more than the average purchase amount?
SELECT * FROM customer;
SELECT customer_id, "purchase_amount_(usd)"
FROM customer
WHERE discount_applied='Yes' AND "purchase_amount_(usd)" >=(SELECT AVG("purchase_amount_(usd)") 
FROM customer);

--03 Which are the top 5 products with the highest average review rating?
SELECT * FROM customer;

SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),2) AS "Average Product Rating"
FROM customer 
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--04 Compare the average purchase amounts between standard and express shipping
SELECT * FROM customer;

SELECT shipping_type , ROUND(AVG("purchase_amount_(usd)"),2) 
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--05 Do subscribed customers spens more? Compare average spend and total revenue between subscribes and non-subscribers.
SELECT * FROM customer;

SELECT subscription_status, COUNT("customer_id") AS "Total Customer",
ROUND(AVG("purchase_amount_(usd)"),2)  AS "Average Spend",
ROUND(SUM("purchase_amount_(usd)"),2)  AS "Total Revenue"
FROM customer 		
Group BY subscription_status 
ORDER BY "Total Revenue" DESC, "Average Spend" DESC;
 
--06 Which 5 products have the highest percentage of purchase with discounts applied?
SELECT * FROM customer;

SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN "discount_applied" = 'Yes' THEN 1 ELSE 0 END) /COUNT(*),2) AS "Discount Rate"
FROM customer
GROUP BY item_purchased
ORDER BY "Discount Rate" DESC
LIMIT 5; 	

--07 Segment customers into new, returing and loyal based on their total number of previous purchases, and show the count of each segment.
SELECT * FROM customer;

WITH "Customer Type" AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN "previous_purchases" = 1 THEN 'New'
	WHEN "previous_purchases" BETWEEN 2 AND 10 THEN 'Returning'
	ELSE  'Loyalty'
	END AS "Customer Segment"
FROM customer
)

SELECT "Customer Segment", COUNT(*) AS "Number of Customers"
FROM "Customer Type"
GROUP BY "Customer Segment"

--08 What are the top 3 most purchased products within each category?
SELECT * FROM customer;

WITH "Item Counts" AS (
SELECT category, item_purchased,
COUNT("customer_id") AS "Total Orders",
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT("customer_id") DESC ) AS "Item Ranked"
FROM customer
GROUP BY category, item_purchased
)
SELECT "Item Ranked", category, item_purchased, "Total Orders"
FROM "Item Counts"
WHERE "Item Ranked" <= 3;
	
--09 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribr?
SELECT * FROM customer;

SELECT subscription_status, 
COUNT(customer_id) AS "Repeated Buyers" 
FROM customer 
WHERE previous_purchases > 5
GROUP BY subscription_status;

--10 What is the revenue contribution of each age group?
SELECT * FROM customer;

SELECT age_group,
SUM("purchase_amount_(usd)") AS "Total Revenue"
FROM customer
Group BY age_group
ORDER BY "Total Revenue" DESC; 


